[package]
name = "notifyi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
daemonize = "0.5.0"
dialoguer = "0.10.3"
libnotify = "1.0.3"
